"use client";

import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle, Clock, FileArrowUp, Plus, SpinnerGap, WarningCircle } from "@phosphor-icons/react";
import { AddRecordModal } from "@/components/add-record-modal";
import { createClient } from "@/lib/supabase/client";

type Dataset = { dataset_id: string; datasets: { name: string; slug: string } };
type Submission = { id: string; dataset: string; type: string; filename: string | null; rows: number; status: string; feedback: string | null; created_at: string; reviewed_at: string | null };
const modules: Record<string, "jobseekers" | "research" | "biometrics"> = { jobseeker_registry: "jobseekers", research_requests: "research", biometric_events: "biometrics" };

export function FocalWorkspace({ profile, onImport }: { profile: { role: "office_focal"; id: string }; onImport: (key: "jobseekers" | "research" | "biometrics") => void }) {
 const [datasets,setDatasets]=useState<Dataset[]>([]); const [submissions,setSubmissions]=useState<Submission[]>([]); const [selected,setSelected]=useState<"jobseekers"|"research"|"biometrics"|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=async()=>{const supabase=createClient();const [grants,items]=await Promise.all([supabase.schema("core").from("user_dataset_grants").select("dataset_id, datasets!inner(id,slug,name)").eq("user_id",profile.id).eq("access_mode","read_write").is("revoked_at",null),supabase.schema("core").rpc("my_data_submissions")]);if(grants.error||items.error)setError("Your assigned datasets or submissions could not be loaded.");else{setDatasets((grants.data??[]) as unknown as Dataset[]);setSubmissions((items.data??[]) as Submission[]);}setLoading(false);};
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const timer=window.setInterval(()=>void load(),15000);return()=>{window.clearTimeout(initial);window.clearInterval(timer);};},[profile.id]);
 return <div className="page"><PageHeader title="My submissions" description="Prepare data for your assigned datasets. Every new record and import is reviewed by a Data Protection Officer before it enters the database."/>{error&&<p className="form-error" role="alert">{error}</p>}<section className="panel focal-assignment"><div className="panel-header"><div><h2>Assigned datasets</h2><p>You can submit records and files. Existing database records stay private to the DPO.</p></div></div>{loading?<div className="empty-state"><SpinnerGap className="spin"/><p>Loading your assignments…</p></div>:datasets.length===0?<div className="empty-state"><WarningCircle/><h3>No dataset assignments</h3><p>Ask your DPO to assign a dataset before submitting information.</p></div>:<div className="focal-dataset-list">{datasets.map((grant)=>{const key=modules[grant.datasets.slug];if(!key)return null;return <article key={grant.dataset_id}><div><strong>{grant.datasets.name}</strong><span>Submissions require DPO approval</span></div><button className="button secondary" onClick={()=>onImport(key)}><FileArrowUp/> Upload &amp; map</button><button className="button primary" onClick={()=>setSelected(key)}><Plus/> Add record</button></article>;})}</div>}</section><section className="panel"><div className="panel-header"><div><h2>Submission history</h2><p>Submitted files and records with reviewer feedback.</p></div><button className="icon-button" onClick={()=>void load()} aria-label="Refresh submissions"><ArrowRight/></button></div>{submissions.length===0?<div className="empty-state"><Clock/><p>Your submissions will appear here.</p></div>:<div className="history-list">{submissions.map((item)=><article key={item.id}><span className={`activity-icon ${item.status==="approved"?"green":item.status==="rejected"?"red":"amber"}`}>{item.status==="approved"?<CheckCircle/>:<Clock/>}</span><div><strong>{item.filename??`Manual entry · ${item.dataset}`}</strong><p>{item.dataset} · {item.rows} row{item.rows===1?"":"s"} · {new Date(item.created_at).toLocaleString("en-PH",{dateStyle:"medium",timeStyle:"short"})}</p>{item.feedback&&<small>DPO feedback: {item.feedback}</small>}</div><span className="badge badge-neutral">{item.status.replaceAll("_"," ")}</span></article>)}</div>}</section>{selected&&<AddRecordModal database={selected} role="office_focal" onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);void load();}}/>}</div>;
}

function PageHeader({title,description}:{title:string;description:string}){return <header className="page-header"><div><h1>{title}</h1><p>{description}</p></div></header>;}