"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle, SpinnerGap, UploadSimple } from "@phosphor-icons/react";

export function Landing({onRequest,onSignIn}:{onRequest:()=>void;onSignIn:()=>void}){return <main className="guest-landing"><div className="guest-landing-brand"><span className="seal"><span>S</span></span><span>Municipality of Siniloan<br/><strong>Enterprise Data Management</strong></span></div><section><p className="guest-kicker">Public access</p><h1>Request municipal data</h1><p>Submit a data or interview request for review by the municipal Data Protection Officer. Staff can sign in to their assigned workspace.</p><div className="guest-actions"><button className="button primary" onClick={onRequest}>Request data <ArrowRight/></button><button className="button secondary" onClick={onSignIn}>Staff sign in</button></div></section><footer>Requests are reviewed before any data is released.</footer></main>}

export function GuestRequestForm({onBack}:{onBack:()=>void}){const [type,setType]=useState("data_request");const [name,setName]=useState("");const [email,setEmail]=useState("");const [institution,setInstitution]=useState("");const [purpose,setPurpose]=useState("");const [identification,setIdentification]=useState<File|null>(null);const [letter,setLetter]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [receipt,setReceipt]=useState<{control_number:string}|null>(null);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError("");const form=new FormData();form.set("request_type",type);form.set("requester_name",name);form.set("email",email);form.set("institution_office",institution);form.set("research_title_purpose",purpose);if(identification)form.set("identification",identification);if(letter)form.set("request_letter",letter);try{const response=await fetch("/api/data-requests",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error??"Your request could not be submitted.");setReceipt(result);}catch(e){setError(e instanceof Error?e.message:"Your request could not be submitted.");}finally{setBusy(false);}};
 return <main className="guest-request-page"><button className="button secondary" onClick={onBack}><ArrowLeft/> Back</button><section className="panel guest-request-card">{receipt?<div className="guest-receipt"><CheckCircle/><h1>Request submitted</h1><p>Your request is in the DPO review queue.</p><strong>Control number: {receipt.control_number}</strong><button className="button primary" onClick={onBack}>Done</button></div>:<><header><h1>Request data</h1><p>Complete the form and attach both your ID and request letter. Images are stored privately for DPO review.</p></header><form onSubmit={submit}><label>Request type<select value={type} onChange={e=>setType(e.target.value)}><option value="data_request">Data Request</option><option value="interview_request">Interview Request</option></select></label><label>Full name<input value={name} onChange={e=>setName(e.target.value)} maxLength={160} required/></label><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} required/></label><label>School / institution / office<input value={institution} onChange={e=>setInstitution(e.target.value)} maxLength={240}/></label><label>Request purpose<textarea value={purpose} onChange={e=>setPurpose(e.target.value)} maxLength={1000} required/></label><label className="guest-file-field"><span>Identification image</span><small>JPG, PNG, or WebP · up to 5 MB</small><span className="button secondary"><UploadSimple/> {identification?.name??"Choose ID image"}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setIdentification(e.target.files?.[0]??null)} required/></span></label><label className="guest-file-field"><span>Request letter image</span><small>JPG, PNG, or WebP · up to 5 MB</small><span className="button secondary"><UploadSimple/> {letter?.name??"Choose request image"}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setLetter(e.target.files?.[0]??null)} required/></span></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?<><SpinnerGap className="spin"/> Sending…</>:<>Submit request <ArrowRight/></>}</button></form></>}</section></main>
}