"use client";

import { useCallback, useEffect, useState } from "react";
import { Archive, ArrowLeft, ArrowRight, Check, CheckCircle, DownloadSimple, FileArrowUp, ShieldCheck, SpinnerGap, ArrowsClockwise, WarningCircle } from "@phosphor-icons/react";

import { createClient as createSupabaseClient } from "@/lib/supabase/client";
import { Badge, PageHeader, databaseMeta, type DatabaseKey } from "./app-shared";

export function ImportFlow({ initialModule }: { initialModule: DatabaseKey }) {
  const [step, setStep] = useState(1);
  const [module, setModule] = useState<DatabaseKey>(initialModule);
  const [file, setFile] = useState<File | null>(null);
  const [confirmed, setConfirmed] = useState(false);
  const [importing, setImporting] = useState(false);
  const [error, setError] = useState("");
  const [preview, setPreview] = useState<{ total:number; valid:number; rejected:number; duplicateRows:number; duplicateImport:{id:string;status:string;source_filename:string;created_at:string;repeated:boolean}|null; preview:Array<Record<string,unknown>>; errors:Array<{source_row_number:number;error_code:string;message:string}> }|null>(null);
  const [result, setResult] = useState<{ jobId?: string; submissionId?: string; pendingReview?: boolean; total: number; accepted: number; rejected: number; duplicateRows:number; errors: Array<{ source_row_number: number; error_code:string; message: string }> } | null>(null);
  const [history,setHistory]=useState<Array<{id:string;source_filename:string;status:string;total_rows:number;processed_rows:number;accepted_rows:number;rejected_rows:number;created_at:string;completed_at:string|null;error_message:string|null}>>([]);
  const [historyLoading,setHistoryLoading]=useState(true);
  const mappings: Record<DatabaseKey, Array<[string, string]>> = {
    jobseekers: [["SURNAME", "Surname"], ["FIRST NAME", "First name"], ["DATE OF BIRTH", "Birth date"], ["CONTACT NUMBER/S", "Mobile number"], ["EMAIL ADDRESS", "Email"]],
    research: [["CATEGORY", "Category"], ["RESEARCHER / REQUESTER NAME", "Requester name"], ["SCHOOL / INSTITUTION / OFFICE", "Institution / office"], ["RESEARCH TITLE / PURPOSE", "Title / purpose"], ["CONTROL NO.", "Control number"]],
    biometrics: [["DEPARTMENT", "Department"], ["NAME", "Person name"], ["NO.", "Personnel number"], ["DATE/TIME", "Event date and time"], ["VERIFYCODE", "Verification method"]],
  };
  const destinationName = databaseMeta[module].name;
  const loadHistory=useCallback(async()=>{const {data}=await createSupabaseClient().schema("core").from("import_jobs").select("id, source_filename, status, total_rows, processed_rows, accepted_rows, rejected_rows, created_at, completed_at, error_message").order("created_at",{ascending:false}).limit(100);setHistory((data??[]) as typeof history);setHistoryLoading(false);},[]);
  useEffect(()=>{const initial=window.setTimeout(()=>{void loadHistory();},0);const timer=window.setInterval(()=>{void loadHistory();},10_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer);};},[loadHistory]);
  const chooseFile = (nextFile: File | null) => {
    setError(""); setResult(null); setPreview(null); setConfirmed(false);
    if (!nextFile) return;
    const extension = nextFile.name.split(".").pop()?.toLowerCase();
    const supported = module === "biometrics" ? ["xlsx", "xls", "csv"] : ["xlsx", "csv"];
    if (!extension || !supported.includes(extension)) { setError(module === "biometrics" ? "Choose an XLS, XLSX, or CSV file." : "Choose an XLSX or CSV file."); return; }
    if (nextFile.size > 25 * 1024 * 1024) { setError("The selected file exceeds the 25 MB limit."); return; }
    setFile(nextFile); setStep(2);
  };
  const runPreview=async()=>{
    if(!file)return;setImporting(true);setError("");
    try{const {data}=await createSupabaseClient().auth.getSession();if(!data.session)throw new Error("Your session expired. Sign in again before importing.");const body=new FormData();body.set("module",module);body.set("mode","preview");body.set("file",file);const response=await fetch("/api/imports",{method:"POST",headers:{Authorization:`Bearer ${data.session.access_token}`},body});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"The file could not be validated.");setPreview(payload);setStep(3);}catch(previewError){setError(previewError instanceof Error?previewError.message:"The file could not be validated.");}finally{setImporting(false);}
  };
  const startImport = async () => {
    if (!file || !confirmed) return;
    setImporting(true); setError("");
    try {
      const { data } = await createSupabaseClient().auth.getSession();
      if (!data.session) throw new Error("Your session expired. Sign in again before importing.");
      const body = new FormData(); body.set("module", module); body.set("mode","commit"); body.set("file", file);
      const response = await fetch("/api/imports", { method: "POST", headers: { Authorization: `Bearer ${data.session.access_token}` }, body });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error ?? "The import could not be completed.");
      setResult(payload); setStep(5); loadHistory();
    } catch (importError) {
      setError(importError instanceof Error ? importError.message : "The import could not be completed.");
    } finally { setImporting(false); }
  };
  const reset = () => { setStep(1); setFile(null); setConfirmed(false); setPreview(null); setResult(null); setError(""); };
  const downloadErrors=(items:Array<{source_row_number:number;error_code:string;message:string}>,name:string)=>{const escape=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;const csv=[["Source row","Error code","Message"],...items.map(item=>[item.source_row_number,item.error_code,item.message])].map(row=>row.map(escape).join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);};
  const downloadJobErrors=async(jobId:string)=>{try{const {data}=await createSupabaseClient().auth.getSession();if(!data.session)throw new Error("Your session expired.");const response=await fetch(`/api/imports?jobId=${encodeURIComponent(jobId)}`,{headers:{Authorization:`Bearer ${data.session.access_token}`}});if(!response.ok){const payload=await response.json();throw new Error(payload.error??"The error report could not be downloaded.");}const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`import-errors-${jobId}.csv`;link.click();URL.revokeObjectURL(url);}catch(downloadError){setError(downloadError instanceof Error?downloadError.message:"The error report could not be downloaded.");}};
  return <div className="page narrow-page"><PageHeader eyebrow="Data operations" title="Import records" description="Preview, validate, and commit source records with a full operational history." /><div className="stepper">{["Upload","Map fields","Preview","Confirm","Complete"].map((x,i)=><div className={step>i+1?"done":step===i+1?"active":""} key={x}><span>{step>i+1?<Check />:i+1}</span><strong>{x}</strong></div>)}</div><section className="panel import-card">
    {error && <p className="form-error" role="alert">{error}</p>}
    {step===1&&<><h2>Choose destination and file</h2><p>Select the destination database. The importer will apply its required fields and use the first worksheet in the file.</p><label>Destination database<select value={module} onChange={(event)=>setModule(event.target.value as DatabaseKey)}><option value="jobseekers">Jobseeker Registry</option><option value="research">Research & Data Requests</option><option value="biometrics">Biometrics Data</option></select></label><label className="dropzone"><FileArrowUp weight="duotone"/><strong>Choose an Excel or CSV file</strong><span>Maximum file size: 25 MB</span><em>{module === "biometrics" ? ".XLS, .XLSX, .CSV" : ".XLSX, .CSV"}</em><input className="visually-hidden" type="file" accept={module === "biometrics" ? ".xls,.xlsx,.csv" : ".xlsx,.csv"} onChange={(event)=>chooseFile(event.target.files?.[0] ?? null)}/></label></>}
    {step===2&&file&&<><div className="import-file"><FileArrowUp/><div><strong>{file.name}</strong><span>{(file.size/1024).toLocaleString(undefined,{maximumFractionDigits:1})} KB · Ready for secure processing</span></div><Badge tone="green"><Check/> Selected</Badge></div><h2>Automatic field mapping</h2><p>The importer recognizes the source columns below. Extra columns are retained as source metadata where supported.</p><div className="mapping-list">{mappings[module].map(([source,destination])=><div key={source}><span>{source}</span><ArrowRight/><strong>{destination}</strong><Badge tone="green">Matched</Badge></div>)}</div></>}
    {step===3&&file&&preview&&<><div className="validation-progress"><CheckCircle weight="fill"/><h2>Preview ready</h2><p>No records have been written. Review the validation results before committing this file.</p></div><div className="validation-stats"><div><strong>{preview.total.toLocaleString()}</strong><span>Source rows</span></div><div><strong>{preview.valid.toLocaleString()}</strong><span>Ready to import</span></div><div><strong>{preview.rejected.toLocaleString()}</strong><span>Validation issues</span></div></div>{(preview.duplicateRows>0||preview.duplicateImport)&&<div className="import-warning"><WarningCircle/><div><strong>Duplicate detection found possible matches</strong><p>{preview.duplicateImport?`This file matches ${preview.duplicateImport.source_filename}, imported ${new Date(preview.duplicateImport.created_at).toLocaleString("en-PH",{dateStyle:"medium",timeStyle:"short"})}.`:""} {preview.duplicateRows>0?`${preview.duplicateRows} repeated row${preview.duplicateRows===1?"":"s"} will be included with a warning.`:""}</p></div></div>}<div className="preview-table"><div className="panel-header"><div><h2>Row preview</h2><p>First {preview.preview.length} valid rows</p></div></div>{preview.preview.map((row,index)=><div key={index}>{Object.entries(row).map(([key,value])=><span key={key}><small>{key.replaceAll("_"," ")}</small><strong>{String(value)}</strong></span>)}</div>)}</div>{preview.errors.length>0&&<div className="issue-list"><div className="import-warning"><WarningCircle/><div><strong>{preview.errors.length.toLocaleString()} rows need attention</strong><p>Invalid rows will be held out of the submission. Download the row details to review them.</p></div></div><button className="button secondary" onClick={()=>downloadErrors(preview.errors,`validation-errors-${file.name}.csv`)}><DownloadSimple/> Download validation errors</button></div>}</>}
    {step===4&&file&&preview&&<><div className="validation-progress"><ShieldCheck weight="fill"/><h2>Ready to submit</h2><p>Valid records will be sent to the DPO for review before they appear in the database.</p></div><div className="import-summary"><div><span>Destination</span><strong>{destinationName}</strong></div><div><span>Import file</span><strong>{file.name}</strong></div><div><span>Ready rows</span><strong>{preview.valid.toLocaleString()}</strong></div><div><span>Rejected rows</span><strong>{preview.rejected.toLocaleString()}</strong></div></div><label className="consent"><input type="checkbox" checked={confirmed} onChange={(event)=>setConfirmed(event.target.checked)}/><span>I reviewed the preview and approve sending these records for DPO review.</span></label></>}
    {step===5&&result&&<><div className="validation-progress"><CheckCircle weight="fill"/><h2>{result.pendingReview?"Sent for DPO review":"Import completed"}</h2><p>{result.pendingReview?`${result.total.toLocaleString()} rows were submitted to the DPO. No records are live until approval.`:`${result.accepted.toLocaleString()} records were added to ${destinationName}.`}</p></div><div className="validation-stats"><div><strong>{result.total.toLocaleString()}</strong><span>Source rows</span></div><div><strong>{result.accepted.toLocaleString()}</strong><span>Imported</span></div><div><strong>{result.rejected.toLocaleString()}</strong><span>Rejected</span></div></div>{result.errors.length>0&&<div className="issue-list"><div className="import-warning"><WarningCircle/><div><strong>{result.errors.length.toLocaleString()} rows need attention</strong><p>Invalid rows were held out. Download the row details to review them.</p></div></div>{result.jobId&&<button className="button secondary" onClick={()=>downloadJobErrors(result.jobId!)}><DownloadSimple/> Download full error report</button>}</div>}{result.jobId&&<div className="import-summary"><div><span>Import job</span><strong>{result.jobId}</strong></div></div>}{result.submissionId&&<div className="import-summary"><div><span>Submission</span><strong>{result.submissionId}</strong></div></div>}</>}
    <div className="import-actions">{result?<button className="button primary" onClick={reset}><FileArrowUp/> Import another file</button>:<><button className="button secondary" onClick={()=>setStep(Math.max(1,step-1))} disabled={step===1||importing}><ArrowLeft/> Back</button>{step===2?<button className="button primary" onClick={runPreview} disabled={!file||importing}>{importing?<><SpinnerGap className="spin"/> Validating…</>:<>Run preview <ArrowRight/></>}</button>:step===3?<button className="button primary" onClick={()=>setStep(4)}>Continue <ArrowRight/></button>:step===4?<button className="button primary" onClick={startImport} disabled={!confirmed||importing}>{importing?<><SpinnerGap className="spin"/> Processing in batches…</>:<>Commit import <FileArrowUp/></>}</button>:null}</>}</div>
  </section><section className="panel import-history"><div className="panel-header"><div><h2>Complete import history</h2><p>Queued, processing, completed, and failed uploads.</p></div><button className="button secondary" onClick={loadHistory}><ArrowsClockwise/> Refresh</button></div>{historyLoading?<div className="empty-state"><SpinnerGap className="spin"/><p>Loading import history…</p></div>:history.length===0?<div className="empty-state"><Archive/><p>No imports recorded yet.</p></div>:<div className="history-list">{history.map(item=>{const percent=item.total_rows?Math.round((item.processed_rows/item.total_rows)*100):0;return <div key={item.id}><span className={`activity-icon ${item.status==="completed"?"green":item.status==="failed"?"red":"amber"}`}><FileArrowUp/></span><div><strong>{item.source_filename}</strong><p>{item.accepted_rows.toLocaleString()} accepted · {item.rejected_rows.toLocaleString()} rejected · {new Date(item.created_at).toLocaleString("en-PH",{dateStyle:"medium",timeStyle:"short"})}</p>{item.status==="processing"&&<span className="import-progress"><i style={{width:`${percent}%`}}/>{percent}% processed</span>}{item.error_message&&<small>{item.error_message}</small>}</div><Badge tone={item.status==="completed"?"green":item.status==="failed"?"red":"amber"}>{item.status.replaceAll("_"," ")}</Badge></div>})}</div>}</section></div>;
}
