DROP FUNCTION core.query_records(text,text,text,text,date,date,text,boolean,integer,integer);
CREATE FUNCTION core.query_records(p_module text,p_search text DEFAULT '',p_status text DEFAULT '',p_secondary text DEFAULT '',p_from date DEFAULT null,p_to date DEFAULT null,p_sort text DEFAULT 'created_at',p_desc boolean DEFAULT true,p_page integer DEFAULT 1,p_size integer DEFAULT 25,p_request_type text DEFAULT '') RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path='' AS $$
DECLARE source_sql text; result jsonb;
BEGIN
 IF p_page<1 OR p_size NOT IN (25,50,100) OR p_sort NOT IN ('created_at','name','status','secondary','record_date','control_number') OR length(p_search)>200 OR length(p_secondary)>200 OR length(p_status)>200 OR p_request_type NOT IN ('','data_request','interview_request') OR p_from>p_to THEN RAISE EXCEPTION 'Invalid record filters or pagination' USING errcode='22023'; END IF;
 CASE p_module
 WHEN 'jobseekers' THEN source_sql:=$q$ SELECT to_jsonb(t) record,id,created_at,concat_ws(' ',first_name,middle_name,surname) name,coalesce(metadata->>'EMPLOYMENT STATUS','') status,coalesce(metadata->>'PREFERRED OCCUPATION/S','') secondary,created_at::date record_date,''::text control_number,''::text request_type,concat_ws(' ',first_name,middle_name,surname,metadata->>'EMPLOYMENT STATUS') search_text FROM jobseekers.people t$q$;
 WHEN 'research' THEN source_sql:=$q$ SELECT to_jsonb(t) record,id,created_at,requester_name name,status::text status,coalesce(category,'') secondary,date_received record_date,coalesce(control_number,'') control_number,coalesce(request_type,'data_request') request_type,concat_ws(' ',control_number,requester_name,institution_office,research_title_purpose,status,category,request_type) search_text FROM research.requests t$q$;
 WHEN 'biometrics' THEN source_sql:=$q$ SELECT to_jsonb(t) record,id,created_at,person_name name,coalesce(attendance_status,'') status,coalesce(external_location_id,'') secondary,(occurred_at AT TIME ZONE 'Asia/Manila')::date record_date,''::text control_number,''::text request_type,concat_ws(' ',person_name,personnel_number,attendance_status,external_location_id,verify_code) search_text FROM biometrics.device_events t$q$;
 ELSE RAISE EXCEPTION 'Unknown module' USING errcode='22023'; END CASE;
 EXECUTE format($q$ WITH source AS MATERIALIZED (%s),matches AS MATERIALIZED (SELECT * FROM source WHERE strpos(lower(search_text),lower(trim(coalesce($1,''))))>0 AND ($2='' OR status=$2) AND strpos(lower(secondary),lower(trim(coalesce($3,''))))>0 AND ($4 IS NULL OR record_date >= $4) AND ($5 IS NULL OR record_date <= $5) AND ($8='' OR request_type=$8)),totals AS (SELECT count(*) total FROM matches),paging AS (SELECT total,least($6::bigint,greatest(1,(total+$7-1)/$7)) page FROM totals),page_rows AS (SELECT record FROM matches ORDER BY %I %s NULLS LAST,id %s LIMIT $7 OFFSET (SELECT (page-1)*$7 FROM paging)) SELECT jsonb_build_object('rows',coalesce((SELECT jsonb_agg(record) FROM page_rows),'[]'::jsonb),'total',(SELECT total FROM paging),'page',(SELECT page FROM paging),'statuses',coalesce((SELECT jsonb_agg(status ORDER BY status) FROM (SELECT DISTINCT status FROM source WHERE status<>'') s),'[]'::jsonb))$q$,source_sql,p_sort,CASE WHEN p_desc THEN 'desc' ELSE 'asc' END,CASE WHEN p_desc THEN 'desc' ELSE 'asc' END) INTO result USING p_search,coalesce(p_status,''),p_secondary,p_from,p_to,p_page,p_size,p_request_type;
 RETURN result;
END;
$$;
REVOKE ALL ON FUNCTION core.query_records(text,text,text,text,date,date,text,boolean,integer,integer,text) FROM public;
GRANT EXECUTE ON FUNCTION core.query_records(text,text,text,text,date,date,text,boolean,integer,integer,text) TO authenticated;